### ISSUE TITLE
Type hint mismatch of QuadraticProgramToQubo.get_compatibility_msg

### ISSUE THREAD

**Issue by t-imamichi** [stefan-woerner/qiskit-aqua#100]
### What is the expected enhancement?

The implementation, return type and docstring of `QuadraticProgramToQubo.get_compatibility_msg` do not match. It should be fixed.
https://github.com/stefan-woerner/qiskit-aqua/blob/optimization-stack/qiskit/optimization/converters/quadratic_program_to_qubo.py#L89

**Comment by stefan-woerner** [comment]
Corrected return type and docstring.
