### ISSUE TITLE
More intuitive and user-friendly interfaces for objective / constraints in QuadraticProgram

### ISSUE THREAD

**Issue by stefan-woerner** [stefan-woerner/qiskit-aqua#64]
Suggestions to improve the user experience for QuadraticProgram:

1. rename
- "ObjectiveInterface" to "QuadraticObjective"
- "Linear/QuadraticConstraintInterface" to "Linear/QuadraticConstraints"
- "VariablesInterface" to "Variables"

2. use scipy.sparse.spmatrix (e.g. dok_matrix) to represent all linear / quadratic terms (in objective and constraints)

3. change interfaces (for all objective and linear/quadratic constraints). Default get_linear / get_quadratic (same for setters) should return / take internal sparse representation. Need to accept variable name or index, and internally map name to index (to be compatible with sparse matrices):

```
# directly set/get internal representation (as scipy.sparse.spmatrix)
get_quadratic() -> spmatrix
set_quadratic(values: spmatrix)

# get/set individual coefficients (indexed by name or integer)
get_quadratic_coefficient(i: Union[str, int], j: Union[str, int])
set_quadratic_coefficient(i: Union[str, int], j: Union[str, int], value: float)

# get/set whole (sparse) matrix as dictionary (key: Tuple[Union[str, int], Union[str, int]], value: float)
get_quadratic_dict()
set_quadratic_dict(values_dict)

# get/set whole (dense) matrix as array
get_quadratic_array()
 set_quadratic_array(values_array)
```

4. get rid of remaining getters/setters for objective/constraints

**Comment by t-imamichi** [comment]
We also need to decide 1/2 problem of quadratic matrix. In CPLEX, the objective takes 1/2Q, but the quadratic constraints take Q (without 1/2).

**Comment by t-imamichi** [comment]
Do you mean "array" `numpy.ndarray` or builtin `list`?

**Comment by stefan-woerner** [comment]
should support both

**Comment by t-imamichi** [comment]
Because their interfaces are different, I think we need to have different methods corresponding to ndarray and list.

**Comment by t-imamichi** [comment]
I see. getter can deal with both in the same way.

**Comment by adekusar-drl** [comment]
@stefan-woerner I was looking through the ADMM again and I think that when you iterate over constraints to collect specific values (e.g. build a matrix with continuous variables only) it is easier to work with a single constraint instead of keeping the index of the current constraint. 

Likely it is a matter of taste but I prefer to separate a list of constraints (or matrix representation) and a single constraint.

**Comment by adekusar-drl** [comment]
Are there any plans when this can be done? Likely it will seriously affect ADMM as the implementation heavily relies on matrices/vectors and now they will be available as a part of interfaces.

**Comment by stefan-woerner** [comment]
This needs to be done asap.

**Comment by adekusar-drl** [comment]
Ok, please let me know how I can help. 
In general, I totally agree with the proposed changes. I really don't like the CPLEX style interface with `*args` and counter intuitive internal structure behind the interfaces.

**Comment by t-imamichi** [comment]
The interface with `*args` is super complicated and I spent so much time to keep the consistency with CPLEX API. If you can discard it, we have to do it first.

**Comment by t-imamichi** [comment]
I'm working on the prototype at https://github.com/t-imamichi/qiskit-aqua/tree/qp-simplify

**Comment by t-imamichi** [comment]
As the first step, I try to revise variables. https://github.com/t-imamichi/qiskit-aqua/blob/qp-simplify/qiskit/optimization/problems/variables.py
I removed all `*args`. There are following getter and setter.
- suppose `item: Union[str, int]` is a variable name or index
- `set_foo(item: Union[str, int], val: float)`
- `get_foo(item: Union[str, int]) -> float`
- `get_all_foo() -> List[float]`

**Comment by t-imamichi** [comment]
I then refactored linear constraints. https://github.com/t-imamichi/qiskit-aqua/blob/qp-simplify/qiskit/optimization/problems/linear_constraints.py
Main changes:
- `add` add one constraint. CPLEX can add multiple constraints at once, but implementation is complicated. So I make it simpler.
- set_foo(item, val)
- get_foo(item)
- get_foo_list()
- get_linear_dict() -> dict
- get_linear_array() -> spmatrix

**Comment by t-imamichi** [comment]
I think set_linear and set_quadratic need to handle a dict of a special form as well as spmatrix and ndarray.
For example, set_linear({'x': 1, 'y':2}) and set_quadratic({('x', 'y'): 1, ('z', 'z'): 2}.
What do you think?

**Comment by t-imamichi** [comment]
I implemented `variables`, `linear_constraints`, `quadratic_constraints`, `quadratic_objective`.
Not yet integrated in `QuadraticProgram`. Could you tell me feedback of the current design?

**Comment by t-imamichi** [comment]
We should take into account existing modeling tools as follows.
- https://www.python-mip.com/
- https://www.cvxpy.org/
- https://github.com/coin-or/pulp
- https://github.com/JuliaOpt/JuMP.jl

**Comment by t-imamichi** [comment]
We are working on a new API at https://github.com/stefan-woerner/qiskit-aqua/tree/new_quadratic_program
