### ISSUE TITLE
IntegerToBinary: naming and quadratic constraints

### ISSUE THREAD

**Issue by Cryoris** [stefan-woerner/qiskit-aqua#65]
### What is the expected enhancement?

The converter from integer to binary variables is currently called `IntegerToBinaryConverter`. If we would rename it to `IntegerToBinaryVariables` I think this would be clearer on what it actually is converting. 

Also it doesn't currently support quadratic, which we should also add as functionality. This should be very similar to the current code, I believe.

**Comment by a-matsuo** [comment]
I totally agree with changing the name. About supporting quadratic constraints, currently my hands are full with implementing `OperatorToOptimizationProblem` converter. I will work on after that.
