### ISSUE TITLE
InequalityToEquality: naming and quadratic constraints

### ISSUE THREAD

**Issue by Cryoris** [stefan-woerner/qiskit-aqua#66]
### What is the expected enhancement?

Since this converter converts constraints this should probably be called `InequalityToEqualityConstraints` instead of `*Converters`. It also fits the naming scheme of the other converters better then.

Also it does not yet support quadratic constraints, which probably can be added in the same way as the linear constraints. Would it be possible to add these, too? 🙂

**Comment by a-matsuo** [comment]
I totally agree with changing the name. About supporting quadratic constraints, currently my hands are full with implementing `OperatorToOptimizationProblem` converter. I will work on after that.
