### ISSUE TITLE
Rename util.py

### ISSUE THREAD

**Issue by t-imamichi** [stefan-woerner/qiskit-aqua#99]
### What is the expected enhancement?

[util.py](https://github.com/stefan-woerner/qiskit-aqua/blob/optimization-stack/qiskit/optimization/util.py) is a very generic file name and placed at the top level of optimization. But it contains only one function [`get_qubo_solutions`](https://github.com/stefan-woerner/qiskit-aqua/blob/optimization-stack/qiskit/optimization/util.py#L20). It should be moved to a relevant directory and renamed with a more informative name.

**Comment by stefan-woerner** [comment]
I moved the functionality to `GroverOptimizer` and deleted util.py.
